#!/bin/bash

set -e

IMAGE=$1
IMAGE_PATH=/tmp/bb/compressed-images/`dirname $IMAGE`
TARGET_PATH=/tmp/bb/compressed-images/$IMAGE
TARGET_IMAGE=${TARGET_PATH}.png
COLOURS=2
BLUR=0x70

echo "Thinking about image ... \"$IMAGE\""

if [ -e $TARGET_IMAGE ]
then
  echo "Skipping; compressed image already exists."
else
  mkdir -p "$IMAGE_PATH"
  # Convert everything to PNG
  convert "${IMAGE}[0]" -blur $BLUR +dither -colors $COLOURS "${TARGET_IMAGE}"
fi

HEIGHT=`identify -format "%h" "${TARGET_IMAGE}"`
WIDTH=`identify -format "%w" "${TARGET_IMAGE}"`
HASH=`base64 "${TARGET_IMAGE}" | tr -d '\n'`
ESCAPED_NAME=`printf "%q" "${IMAGE}"`

echo "{\"height\": $HEIGHT, \"width\": $WIDTH, \"base64String\": \"$HASH\", \"name\": \"$ESCAPED_NAME\"}">>metadata/images.jsonl
