#!/usr/bin/env sh

set -e

# Remove metadata, if it's there
if [ -e metadata/images.jsonl ]
then
  rm metadata/images.jsonl
fi

# Make some more. Can't do in parallel.
find images  -type f -print0 | xargs -P 1 -0 -I {} \
   ./scripts/make-compressed-image "{}"
